# fly.toml app configuration file generated for infinit-feeding on 2024-04-08T13:13:17+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'infinit-feeding'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 3000 
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'performance'
  cpus = 1
