// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
	"time"
)

type BulkUploadEvent struct {
	Type        string `json:"type"`
	Data        []byte `json:"data"`
	Version     int64  `json:"version"`
	Timestamp   int64  `json:"timestamp"`
	AggregateID string `json:"aggregateId"`
}

type BulkUploadProjection struct {
	ID                      string       `json:"id"`
	Status                  string       `json:"status"`
	TargetDomain            string       `json:"targetDomain"`
	FileID                  string       `json:"fileId"`
	InitiatedAt             time.Time    `json:"initiatedAt"`
	CompletedAt             sql.NullTime `json:"completedAt"`
	InvalidationStartedAt   sql.NullTime `json:"invalidationStartedAt"`
	InvalidationCompletedAt sql.NullTime `json:"invalidationCompletedAt"`
	TotalRecords            int64        `json:"totalRecords"`
	ProcessedRecords        int64        `json:"processedRecords"`
	FailedRecords           int64        `json:"failedRecords"`
	UploadMetadata          string       `json:"uploadMetadata"`
	Version                 int64        `json:"version"`
	UpdatedAt               sql.NullTime `json:"updatedAt"`
}
